version: '3.8'

services:
  app:
    build: .
    container_name: api_catalog
    ports:
      - "8014:3333"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
